export const rqSelectClassNames = {
  trigger: "rqs-trigger",
  triggerValue: "rqs-trigger__value",
  triggerIcon: "rqs-trigger__icon",
  spinner: "rqs-spinner",
  content: "rqs-content",
  searchWrapper: "rqs-search-wrapper",
  searchIcon: "rqs-search__icon",
  searchInput: "rqs-search",
  scrollArea: "rqs-scroll-area--padded",
  list: "rqs-list",
  message: "rqs-message",
  item: "rqs-item",
  itemIndicator: "rqs-item__indicator",
  itemCheckIcon: "rqs-item__check-icon",
  placeholder: "rqs-placeholder",
  pill: "rqs-pill",
  pillRemove: "rqs-pill-remove",
  clear: "rqs-clear",
} as const;
